<?php
$folders = ['Admin', 'operation', 'client'];
$modified = 0;

foreach ($folders as $folder) {
    $files = glob(__DIR__ . '/' . $folder . '/*.php');
    foreach ($files as $file) {
        $content = file_get_contents($file);
        
        $start_tag = "customize: function (doc) {";
        $end_tag = "doc.footer = function (currentPage, pageCount) {";
        
        $pos1 = strpos($content, $start_tag);
        
        // Loop through all instances of pdfHtml5 customize
        $offset = 0;
        $changed = false;
        
        while (($pos1 = strpos($content, $start_tag, $offset)) !== false) {
            $pos2 = strpos($content, $end_tag, $pos1);
            if ($pos2 !== false) {
                // Get the string in between
                $between = substr($content, $pos1 + strlen($start_tag), $pos2 - ($pos1 + strlen($start_tag)));
                
                // Find title
                $title = "Report";
                if (preg_match('/let titleText = `([^`]+)`/', $between, $m)) {
                    $title = $m[1];
                } elseif (preg_match('/\{ text: [\'"`]([^\'"`]+)[\'"`]/', $between, $m)) {
                    $title = $m[1];
                }
                
                // Construct new inner block
                $new_inner = <<<EOD

        let imgBase64 = typeof logoBase64 !== 'undefined' ? logoBase64 : (typeof COMPANY_LOGO_BASE64 !== 'undefined' ? COMPANY_LOGO_BASE64 : '');
        let titleText = `$title`;
        
        let headerCols = [
            {
                width: '30%',
                text: [
                    { text: 'Generated By: ', bold: true },
                    { text: '<?php echo isset(\$_SESSION["mobile"]) ? \$_SESSION["mobile"] : (isset(\$_SESSION["client_mobile"]) ? \$_SESSION["client_mobile"] : "User"); ?>\\n' },
                    { text: 'Date: ', bold: true },
                    { text: typeof now !== 'undefined' ? now.toLocaleString('en-IN') : new Date().toLocaleString('en-IN') }
                ],
                fontSize: 9,
                alignment: 'left'
            },
            {
                width: imgBase64 ? '40%' : '70%',
                stack: [
                    { text: 'SMART TOILET', alignment: 'center', fontSize: 16, bold: true },
                    { text: titleText, alignment: 'center', fontSize: 12, bold: true }
                ]
            }
        ];
        
        if (imgBase64) {
            headerCols.push({
                width: '30%',
                image: imgBase64,
                fit: [60, 60],
                alignment: 'right'
            });
        }
        
        doc.content.unshift({
            columns: headerCols,
            margin: [0, 0, 0, 10]
        });

        const table = doc.content.find(c => c.table);
        if (table) {
            table.alignment = 'center';
            table.table.body.forEach((row, rowIndex) => {
                row.forEach(cell => {
                    cell.alignment = 'center';
                    cell.valign = 'middle';
                    cell.fontSize = rowIndex === 0 ? 9 : 8;
                    if (rowIndex === 0) cell.bold = true;
                });
            });
        }

        
EOD;
                
                // Replace in string
                $content = substr_replace($content, $new_inner, $pos1 + strlen($start_tag), $pos2 - ($pos1 + strlen($start_tag)));
                $changed = true;
                
                // Advance offset
                $offset = $pos1 + strlen($start_tag) + strlen($new_inner);
            } else {
                $offset = $pos1 + strlen($start_tag);
            }
        }
        
        if ($changed) {
            file_put_contents($file, $content);
            echo "Cleaned up PDF logic in: $file\n<br>";
            $modified++;
        }
    }
}
echo "Done. Fixed $modified files.";
?>
