<?php
$folders = ['Admin', 'operation', 'client'];
$modified = 0;

foreach ($folders as $folder) {
    $files = glob(__DIR__ . '/' . $folder . '/*.php');
    foreach ($files as $file) {
        $content = file_get_contents($file);
        
        // Find customize: function (doc) {
        // Then find doc.footer = function (currentPage, pageCount) {
        // Replace everything in between!
        
        $pattern = '/(customize:\s*function\s*\(doc\)\s*\{).*?(doc\.footer\s*=\s*function\s*\(currentPage,\s*pageCount\)\s*\{)/s';
        
        $new_content = preg_replace_callback($pattern, function($matches) {
            // Find the report title from the matched string before wiping it
            $title = "Report";
            if (preg_match('/let titleText = `([^`]+)`/', $matches[0], $m)) {
                $title = $m[1];
            } elseif (preg_match('/\{ text: [\'"`]([^\'"`]+)[\'"`]/', $matches[0], $m)) {
                $title = $m[1];
            }
            
            $new_unshift = <<<EOD
        let imgBase64 = typeof logoBase64 !== 'undefined' ? logoBase64 : (typeof COMPANY_LOGO_BASE64 !== 'undefined' ? COMPANY_LOGO_BASE64 : '');
        let titleText = `$title`;
        
        let headerCols = [
            {
                width: '30%',
                text: [
                    { text: 'Generated By: ', bold: true },
                    { text: '<?php echo isset(\$_SESSION["mobile"]) ? \$_SESSION["mobile"] : (isset(\$_SESSION["client_mobile"]) ? \$_SESSION["client_mobile"] : "User"); ?>\\n' },
                    { text: 'Date: ', bold: true },
                    { text: typeof now !== 'undefined' ? now.toLocaleString('en-IN') : new Date().toLocaleString('en-IN') }
                ],
                fontSize: 9,
                alignment: 'left'
            },
            {
                width: imgBase64 ? '40%' : '70%',
                stack: [
                    { text: 'SMART TOILET', alignment: 'center', fontSize: 16, bold: true },
                    { text: titleText, alignment: 'center', fontSize: 12, bold: true }
                ]
            }
        ];
        
        if (imgBase64) {
            headerCols.push({
                width: '30%',
                image: imgBase64,
                fit: [60, 60],
                alignment: 'right'
            });
        }
        
        doc.content.unshift({
            columns: headerCols,
            margin: [0, 0, 0, 10]
        });

        const table = doc.content.find(c => c.table);
        if (table) {
            table.alignment = 'center';
            table.table.body.forEach((row, rowIndex) => {
                row.forEach(cell => {
                    cell.alignment = 'center';
                    cell.valign = 'middle';
                    cell.fontSize = rowIndex === 0 ? 9 : 8;
                    if (rowIndex === 0) cell.bold = true;
                });
            });
        }

        
EOD;
            return $matches[1] . "\n" . $new_unshift . $matches[2];
        }, $content);
        
        if ($new_content && $new_content !== $content) {
            file_put_contents($file, $new_content);
            echo "Cleaned up PDF logic in: $file\n<br>";
            $modified++;
        }
    }
}
echo "Done. Fixed $modified files.";
?>
