<?php
$folders = ['Admin', 'operation', 'client'];
$modified = 0;

foreach ($folders as $folder) {
    $files = glob(__DIR__ . '/' . $folder . '/*.php');
    foreach ($files as $file) {
        $content = file_get_contents($file);
        
        // Find the customize block for pdfHtml5
        $pdf_start = strpos($content, "customize: function (doc) {");
        if ($pdf_start !== false) {
            
            // We need to replace the entire unshift logic to conditionally handle the image
            // Let's find the end of doc.content.unshift({ ... });
            $unshift_start = strpos($content, "doc.content.unshift({", $pdf_start);
            $unshift_end = strpos($content, "});", $unshift_start) + 3;
            
            if ($unshift_start !== false && $unshift_end !== false) {
                
                // Extract the report title which might be hardcoded in the string
                preg_match("/\{ text: ['`\"]([^'\"`]+)['`\"],\s*alignment:\s*'center',\s*fontSize:\s*12,\s*bold:\s*true \}/", $content, $matches);
                $report_title = isset($matches[1]) ? $matches[1] : "Report";
                
                // Ensure we use backticks for the title so variables like ${timestamp} resolve
                $new_unshift = <<<EOD
        let imgBase64 = typeof logoBase64 !== 'undefined' ? logoBase64 : (typeof COMPANY_LOGO_BASE64 !== 'undefined' ? COMPANY_LOGO_BASE64 : '');
        let titleText = `$report_title`;
        
        let headerCols = [
            {
                width: '30%',
                text: [
                    { text: 'Generated By: ', bold: true },
                    { text: '<?php echo isset(\$_SESSION["mobile"]) ? \$_SESSION["mobile"] : (isset(\$_SESSION["client_mobile"]) ? \$_SESSION["client_mobile"] : "User"); ?>\\n' },
                    { text: 'Date: ', bold: true },
                    { text: typeof now !== 'undefined' ? now.toLocaleString('en-IN') : new Date().toLocaleString('en-IN') }
                ],
                fontSize: 9,
                alignment: 'left'
            },
            {
                width: imgBase64 ? '40%' : '70%',
                stack: [
                    { text: 'SMART TOILET', alignment: 'center', fontSize: 16, bold: true },
                    { text: titleText, alignment: 'center', fontSize: 12, bold: true }
                ]
            }
        ];
        
        if (imgBase64) {
            headerCols.push({
                width: '30%',
                image: imgBase64,
                fit: [60, 60],
                alignment: 'right'
            });
        }
        
        doc.content.unshift({
            columns: headerCols,
            margin: [0, 0, 0, 10]
        });
EOD;

                $before = substr($content, 0, $unshift_start);
                $after = substr($content, $unshift_end);
                
                $new_content = $before . $new_unshift . $after;
                
                if ($new_content !== $content) {
                    file_put_contents($file, $new_content);
                    echo "Fixed PDF logic in: $file\n<br>";
                    $modified++;
                }
            }
        }
    }
}
echo "Done. Fixed $modified files.";
?>
