import os
import re
import glob

# Search in Admin, operation, client
folders = [
    'Admin',
    'operation',
    'client'
]

# Pattern to extract report title
# e.g. text: 'All Logs Report'
title_pattern = re.compile(r"text:\s*['\"]([^'\"]+)['\"]\s*,\s*alignment:\s*'center'")

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    if "extend: 'pdfHtml5'" not in content or "extend: 'print'" not in content:
        return False

    # Extract Title
    title_match = title_pattern.search(content)
    report_title = title_match.group(1) if title_match else "Report"

    # Define the new PDF block
    pdf_block = """{
    extend: 'pdfHtml5',
    filename: fileName,
    orientation: 'landscape',
    pageSize: 'A4',
    title: '',
    className: 'dt-btn-custom',
    exportOptions: { columns: ':visible' },
    customize: function (doc) {
        doc.content.unshift({
            columns: [
                {
                    width: '30%',
                    text: [
                        { text: 'Generated By: ', bold: true },
                        { text: '<?php echo isset($_SESSION["mobile"]) ? $_SESSION["mobile"] : (isset($_SESSION["client_mobile"]) ? $_SESSION["client_mobile"] : "User"); ?>\\n' },
                        { text: 'Date: ', bold: true },
                        { text: now.toLocaleString('en-IN') }
                    ],
                    fontSize: 9,
                    alignment: 'left'
                },
                {
                    width: '40%',
                    stack: [
                        { text: 'SMART TOILET', alignment: 'center', fontSize: 16, bold: true },
                        { text: '""" + report_title + """', alignment: 'center', fontSize: 12, bold: true }
                    ]
                },
                {
                    width: '30%',
                    image: logoBase64,
                    fit: [60, 60],
                    alignment: 'right'
                }
            ],
            margin: [0, 0, 0, 10]
        });

        const table = doc.content.find(c => c.table);
        if (table) {
            table.alignment = 'center';
            table.table.body.forEach((row, rowIndex) => {
                row.forEach(cell => {
                    cell.alignment = 'center';
                    cell.valign = 'middle';
                    cell.fontSize = rowIndex === 0 ? 9 : 8;
                    if (rowIndex === 0) cell.bold = true;
                });
            });
        }

        doc.footer = function (currentPage, pageCount) {
            return {
                columns: [
                    { width: '*', text: '', alignment: 'left' },
                    {
                        width: 'auto',
                        text: 'Copyright © Aarya Group of Industries Nashik, Maharashtra, India.',
                        alignment: 'center',
                        fontSize: 8
                    },
                    {
                        width: '*',
                        text: 'Page ' + currentPage.toString() + ' of ' + pageCount,
                        alignment: 'right',
                        fontSize: 8,
                        margin: [0, 0, 20, 0]
                    }
                ],
                margin: [20, 0, 20, 10]
            };
        };
    }
}"""

    # Define the new Print block
    print_block = """{
    extend: 'print',
    title: '',
    className: 'dt-btn-custom',
    exportOptions: { columns: ':visible' },
    customize: function (win) {
        $(win.document.body).css('font-size', '12px');
        $(win.document.body).find('h1').remove();
        
        let genBy = '<?php echo isset($_SESSION["mobile"]) ? $_SESSION["mobile"] : (isset($_SESSION["client_mobile"]) ? $_SESSION["client_mobile"] : "User"); ?>';
        let dateStr = now.toLocaleString('en-IN');
        
        $(win.document.body).prepend(`
            <div style="margin-bottom:15px; border-bottom: 2px solid #000; padding-bottom: 10px;">
                <div style="display:flex; justify-content:space-between; align-items:center;">
                    <div style="width:30%; font-size:11px;">
                        <div><b>Generated By:</b> ${genBy}</div>
                        <div><b>Date:</b> ${dateStr}</div>
                    </div>
                    <div style="text-align:center; width:40%;">
                        <div style="font-size:18px; font-weight:bold;">SMART TOILET</div>
                        <div style="font-size:14px; font-weight:bold;">""" + report_title + """</div>
                    </div>
                    <div style="width:30%; text-align:right;">
                        <img src="${logoPath}" style="height:50px;">
                    </div>
                </div>
            </div>
        `);

        $(win.document.body).append(`
            <style>
            @media print {
                @page { margin-bottom: 35mm; }
                .dt-print-footer {
                    position: fixed;
                    bottom: 0;
                    left: 0;
                    right: 0;
                    height: 22mm;
                    border-top: 1px solid #000;
                    font-size: 11px;
                    font-weight: bold;
                    line-height: 18px;
                    padding: 10px 40px;
                    background: #fff;
                    display: flex;
                    justify-content: center;
                }
            }
            </style>
            <div class="dt-print-footer">
                <div>Copyright © Aarya Group of Industries Nashik, Maharashtra, India.</div>
            </div>
        `);
    }
}"""

    # Replace pdfHtml5 block
    content = re.sub(
        r"\{\s*extend:\s*['\"]pdfHtml5['\"].*?(?=(,\s*\{\s*extend:\s*['\"]print['\"]|\}\s*\]))",
        pdf_block,
        content,
        flags=re.DOTALL
    )
    
    # Replace print block
    content = re.sub(
        r"\{\s*extend:\s*['\"]print['\"].*?(?=\}\s*\])",
        print_block + "\n            ",
        content,
        flags=re.DOTALL
    )

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
        
    return True

modified = 0
for folder in folders:
    for filepath in glob.glob(os.path.join(folder, '*.php')):
        if process_file(filepath):
            print("Updated:", filepath)
            modified += 1

print(f"Done. Modified {modified} files.")
