<?php
$folders = ['Admin', 'operation', 'client'];
$modified = 0;

$pdf_block = <<<EOD
{
    extend: 'pdfHtml5',
    filename: fileName,
    orientation: 'landscape',
    pageSize: 'A4',
    title: '',
    className: 'dt-btn-custom',
    exportOptions: { columns: ':visible' },
    customize: function (doc) {
        doc.content.unshift({
            columns: [
                {
                    width: '30%',
                    text: [
                        { text: 'Generated By: ', bold: true },
                        { text: '<?php echo isset(\$_SESSION["mobile"]) ? \$_SESSION["mobile"] : (isset(\$_SESSION["client_mobile"]) ? \$_SESSION["client_mobile"] : "User"); ?>\\n' },
                        { text: 'Date: ', bold: true },
                        { text: now.toLocaleString('en-IN') }
                    ],
                    fontSize: 9,
                    alignment: 'left'
                },
                {
                    width: '40%',
                    stack: [
                        { text: 'SMART TOILET', alignment: 'center', fontSize: 16, bold: true },
                        { text: '%%REPORT_TITLE%%', alignment: 'center', fontSize: 12, bold: true }
                    ]
                },
                {
                    width: '30%',
                    image: logoBase64,
                    fit: [60, 60],
                    alignment: 'right'
                }
            ],
            margin: [0, 0, 0, 10]
        });

        const table = doc.content.find(c => c.table);
        if (table) {
            table.alignment = 'center';
            table.table.body.forEach((row, rowIndex) => {
                row.forEach(cell => {
                    cell.alignment = 'center';
                    cell.valign = 'middle';
                    cell.fontSize = rowIndex === 0 ? 9 : 8;
                    if (rowIndex === 0) cell.bold = true;
                });
            });
        }

        doc.footer = function (currentPage, pageCount) {
            return {
                columns: [
                    { width: '*', text: '', alignment: 'left' },
                    {
                        width: 'auto',
                        text: 'Copyright © Aarya Group of Industries Nashik, Maharashtra, India.',
                        alignment: 'center',
                        fontSize: 8
                    },
                    {
                        width: '*',
                        text: 'Page ' + currentPage.toString() + ' of ' + pageCount,
                        alignment: 'right',
                        fontSize: 8,
                        margin: [0, 0, 20, 0]
                    }
                ],
                margin: [20, 0, 20, 10]
            };
        };
    }
}
EOD;

$print_block = <<<EOD
{
    extend: 'print',
    title: '',
    className: 'dt-btn-custom',
    exportOptions: { columns: ':visible' },
    customize: function (win) {
        $(win.document.body).css('font-size', '12px');
        $(win.document.body).find('h1').remove();
        
        let genBy = '<?php echo isset(\$_SESSION["mobile"]) ? \$_SESSION["mobile"] : (isset(\$_SESSION["client_mobile"]) ? \$_SESSION["client_mobile"] : "User"); ?>';
        let dateStr = now.toLocaleString('en-IN');
        
        $(win.document.body).prepend(`
            <div style="margin-bottom:15px; border-bottom: 2px solid #000; padding-bottom: 10px;">
                <div style="display:flex; justify-content:space-between; align-items:center;">
                    <div style="width:30%; font-size:11px;">
                        <div><b>Generated By:</b> \${genBy}</div>
                        <div><b>Date:</b> \${dateStr}</div>
                    </div>
                    <div style="text-align:center; width:40%;">
                        <div style="font-size:18px; font-weight:bold;">SMART TOILET</div>
                        <div style="font-size:14px; font-weight:bold;">%%REPORT_TITLE%%</div>
                    </div>
                    <div style="width:30%; text-align:right;">
                        <img src="\${logoPath}" style="height:50px;">
                    </div>
                </div>
            </div>
        `);

        $(win.document.body).append(`
            <style>
            @media print {
                @page { margin-bottom: 35mm; }
                .dt-print-footer {
                    position: fixed;
                    bottom: 0;
                    left: 0;
                    right: 0;
                    height: 22mm;
                    border-top: 1px solid #000;
                    font-size: 11px;
                    font-weight: bold;
                    line-height: 18px;
                    padding: 10px 40px;
                    background: #fff;
                    display: flex;
                    justify-content: center;
                }
            }
            </style>
            <div class="dt-print-footer">
                <div>Copyright © Aarya Group of Industries Nashik, Maharashtra, India.</div>
            </div>
        `);
    }
}
EOD;

foreach ($folders as $folder) {
    $files = glob(__DIR__ . '/' . $folder . '/*.php');
    foreach ($files as $file) {
        $content = file_get_contents($file);
        
        if (strpos($content, "sheetData.append(footerRow);") !== false) {
            
            // Extract title
            preg_match("/const fileName = [`'\"]([^`-`'\"]+)/", $content, $matches);
            $report_title = isset($matches[1]) ? trim($matches[1]) : "Report";
            
            $new_pdf = str_replace('%%REPORT_TITLE%%', $report_title, $pdf_block);
            $new_print = str_replace('%%REPORT_TITLE%%', $report_title, $print_block);
            
            // Cleanup and replace everything between excelHtml5 and the end of the buttons array
            $pattern = "/(sheetData\.append\(footerRow\);\s*\}\s*\},\s*).*?(?=\]\s*\}\);)/s";
            $replacement = "$1\n            " . $new_pdf . ",\n\n            " . $new_print . "\n\n            ";
            
            $new_content = preg_replace($pattern, $replacement, $content);
            
            if ($new_content && $new_content !== $content) {
                file_put_contents($file, $new_content);
                echo "Cleaned and Updated: $file\n<br>";
                $modified++;
            }
        }
    }
}
echo "Done. Fixed $modified files.";
?>
